version: '3.8'

services:
  todo_api:
    build:
      context: .
      dockerfile: ./dockers/api/Dockerfile
    command: yarn start:dev
    ports:
      - 3000
    depends_on:
      - mysql
      - redis
    networks:
      - todo
    volumes:
      - ./:/app
    restart: unless-stopped

  mysql:
    image: mysql:8.0.25
    container_name: todo_mysql
    restart: unless-stopped
    tty: true
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-todos}
      MYSQL_USER: ${DB_USERNAME:-seakmeng}
      MYSQL_PASSWORD: ${DB_PASSWORD:-password}
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./dockers/mysql:/var/lib/mysql
    networks:
      - todo

  nginx:
    image: nginx:1.21.6
    container_name: todo_nginx
    restart: always
    volumes:
      - ./dockers/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8001:80
    networks:
      - todo
    depends_on:
      - todo_api

networks:
  todo:
    external:
      name: user
